apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: g4
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
          - containerPort: 6379
        volumeMounts:
          - mountPath: "/home/data"
            name: pv-redis
      volumes:
        - name: pv-redis
          persistentVolumeClaim:
            claimName: pvc-redis
      