apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-es-g4
  namespace: g4
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /home/user1/share
    server: 10.4.97.6