apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: g4
  labels:
    app: elasticsearch
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 30059
  selector:
    app: elasticsearch
