apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana-access
  namespace: monitoring
spec:
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30077
  selector:
    app: grafana
  type: NodePort
