apiVersion: v1
kind: Service
metadata:
  name: catalog-api-service
  namespace: g4
spec:
  type: NodePort
  #clusterIP: 10.107.244.160
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32001
      name: http
  selector:
    app: catalog-api