apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: g4
  labels:
    app: keycloak
spec:
  ports:
    - port: 8085
      targetPort: 8080
      nodePort: 30089
  selector:
    app: keycloak
  type: NodePort
