apiVersion: v1
kind: Service
metadata:
  name: ocelot-gateway-service
  namespace: g4
spec:
  loadBalancerIP: 10.4.98.10
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: ocelot-gateway
