apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
  name: kibana
  namespace: g4
spec:
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 30061
  selector:
    app: kibana
  type: NodePort