apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-catalog-db
  namespace: g4
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi