apiVersion: v1
kind: Service
metadata:
  name: catalog-mssql-service
  namespace: g4
spec:
 type: NodePort
 selector:
    app: catalog-mssql
 ports:
  - port: 1433
    targetPort: 1433
    nodePort: 32767
